[workspace]
members = [
    "crash_orm",
    "crash_orm_derive",
    "crash_orm_migration", "crash_orm_test",
]
resolver = "2"

[workspace.dependencies]
tokio-postgres = "0.7.8"
syn = "^2.0"
quote = "^1.0"
tokio = "1.29.1"
tokio-test = "0.4.4"
async-trait = "^0.1"
rust_decimal = "1.32.0"
chrono = "^0.4"
uuid = "^1.8"
serde = "^1.0"
serde_json = "^1.0"
convert_case = "^0.6.0"
#crash_orm = "0.1.5"
#crash_orm_derive = "0.1.5"
crash_orm.path = "crash_orm"
crash_orm_derive.path = "crash_orm_derive"
