[workspace]
members = [
    "crash_orm",
    "crash_orm_derive",
    "crash_orm_migration",
]
resolver = "2"

[workspace.dependencies]
tokio-postgres = "0.7.8"
syn = "^2.0"
quote = "^1.0"
tokio = "1.29.1"
async-trait = "^0.1"
rust_decimal = "1.32.0"
chrono = "^0.4"
uuid = "1.4.1"
serde = "^1.0"
serde_json = "^1.0"
lazy_static = "1.4.0"
async_once = "0.2.6"
crash_orm = "0.1.3"
crash_orm_derive = "0.1.3"