[workspace]
members = [
    "crash_orm",
    "crash_orm_derive",
    "example_app",
]

[workspace.dependencies]
tokio-postgres = "0.7.8"
syn = "2.0.28"
quote = "1.0.32"
tokio = "1.29.1"
async-trait = "0.1.73"