[package]
name = "crash_orm_migration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crash_orm = { workspace = true, features = ["with-chrono"] }
chrono.workspace = true