[package]
name = "crash_orm"
version = "0.1.0"
edition = "2021"

[features]
default = []
macros = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crash_orm_derive = { path = "../crash_orm_derive" }
tokio-postgres = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
rust_decimal = { workspace = true, features = ["db-tokio-postgres"] }