[package]
name = "crash_orm_rocket_derive"
version = "0.6.3"
edition = "2021"

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }

[lib]
proc-macro = true

[features]
default = []
crud = []