name: Welcome new contributors

on:
  issues:
    types:
      - opened

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thank you for opening your first issue in this repo!
            I will review this issue as soon as possible.
          label: Good First Issue