name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*

jobs:
  test:
    name: Test ORM
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: crash_orm_test
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Cargo test
        run: cargo test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/crash_orm_test
  create-release:
    if: github.repository_owner == 'Cr4shd3v'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          title: $version
          branch: master|v[0-9]+
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog: CHANGELOG.md