name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*

jobs:
  create-release:
    if: github.repository_owner == 'Cr4shd3v'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          title: $version
          branch: master|v[0-9]+
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo publish --token ${CRATES_TOKEN} -p crash_orm_derive
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
      - run: cargo publish --token ${CRATES_TOKEN} -p crash_orm
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}